name: mp-stats-legacy-viewer
description: MP Stats Legacy Viewer
version: 0.0.3
appVersion: v0.3.2
apiVersion: v2
home: https://github.com/timschoenle/charts
sources:
  - https://github.com/TimSchoenle/mp-stats-legacy-viewer
maintainers:
  - name: Tim Sch√∂nle
    email: contact@tim-schoenle.de
dependencies:
  - name: common
    version: 0.1.2
    repository: "file://../common"