apiVersion: v2
name: cloudflare-access-webhook-redirect
description: A Helm chart for deploying the Cloudflare Access Webhook Redirect service. This service acts as an authentication proxy that validates requests using Cloudflare Access Service Auth tokens before forwarding them to target backend services.
type: application
version: 2.1.1
appVersion: v0.3.11
keywords:
  - cloudflare
  - webhook
  - redirect
  - authentication
home: https://github.com/TimSchoenle/cloudflare-access-webhook-redirect
sources:
  - https://github.com/TimSchoenle/cloudflare-access-webhook-redirect
  - https://github.com/TimSchoenle/helm-charts
maintainers:
  - name: Tim Sch√∂nle
    url: https://github.com/TimSchoenle
dependencies:
  - name: common
    version: 0.1.2
    repository: "file://../common"